### ISSUE TITLE
Why is SoapService.cs in the iOS/Droid specific projects

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [xamarin/xamarin-forms-samples#142]
This class seems to be identically for both cases. Why is it in the platform specific part and not in the portable/shared part?

**Comment by davidbritch** [comment]
Apologies for the delay in responding to your issue.

`SoapService.cs` is in the iOS and Droid projects, rather than the PCL, because the `ASMXService` on which `SoapService` is dependent is platform-specific to the iOS and Droid project. `ASMXService`, which is a web service reference, can't be added to the PCL for an ASMX service.
