### ISSUE TITLE
Pinch gesture after changing orientation loses its center

### ISSUE THREAD

**Issue by RogerSchmidlin** [xamarin/xamarin-forms-samples#153]
Using you sample code for the PinchGesture, I noticed that after zooming and then turn the screen orientation, the picture is not adjusted to the screen anymore. Any work around or suggestion for this problem?

**Comment by davidbritch** [comment]
Hi @RogerSchmidlin 

Four years to respond to an issue must be a new record. Apologies for the long delay.

Looks like you've since found the solution to your issue (https://forums.xamarin.com/discussion/74168/full-screen-image-viewer-with-pinch-to-zoom-pan-to-move-tap-to-show-captions-for-xamarin-forms) so I'll close this issue.
