### ISSUE TITLE
Native2Forms using FreshMVVM

### ISSUE THREAD

**Issue by sayaleepote** [xamarin/xamarin-forms-samples#157]
How to navigate from Xamarin.ios view controller to a xamarin.forms set up using FreshMVVM. The application then needs to work with forms for 2-3 pages and then switch back to the xamarin.ios page that it initially started the navigation from.

**Comment by EmilAlipiev** [comment]
I dont think FreshMVVM supports native to XF navigation. what you are looking for is more cross mvvm I think

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

The Native2Forms samples has been re-written since your initial query, and now uses [Native Forms](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/platform/native-forms). With this approach, Xamarin.Forms pages can be mixed with view controllers, as the navigation is handled completely with Xamarin.iOS native code.
