### ISSUE TITLE
TabbedPageWithNavigation: iOS: Navigation doesn't work when item appears in More... menu.

### ISSUE THREAD

**Issue by craigmj** [xamarin/xamarin-forms-samples#177]
When running the TabbedPageWithNavigation on iOS, If you duplicate the NavigationPage elements in MainPage.xaml :

	<NavigationPage Title="Schedule" Icon="schedule.png">
		<x:Arguments>
			<local:SchedulePage />
		</x:Arguments>
	</NavigationPage>

until one of these duplicates appears in the More... menu, the Navigation no longer works...

**Comment by conceptdev** [comment]
Hi @craigmj, bugs in Xamarin.Forms itself should be raised on the open source repo https://github.com/xamarin/xamarin.forms -- this issues list is monitored mainly for broken samples that appear on https://developer.xamarin.com/samples

Since it has been some time since this post, hopefully the bug has been fixed by now.
