### ISSUE TITLE
Necessary to unsubscribe from button += events?

### ISSUE THREAD

**Issue by makerofthings7** [xamarin/xamarin-forms-samples#188]
I'm just starting out, and see that the events for the Navigation forms samples (WorkingWithNavigation) don't unsubscribe the button.

In iOS I would need to unsubscribe to prevent a memory leak.  Is this still necessary in Xam.Forms?

**Comment by hvaughan3** [comment]
This is definitely necessary to prevent memory leaks. That is one reason why using a control's `Command` is recommended over one of it's events.

In a `ContentPage` you can override `ContentPage.OnAppearing()` and  `ContentPage.OnDisappearing()` to subscribe and unsubscribe. In a control or `ContentView`, you can override `OnParentSet()` and do something like this:

    Button _myButton = new Button();

    private override void OnParentSet() {
        base.OnParentSet();

        if(Parent == null) {
            _myButton.Clicked -= OnMyButtonClicked;
        } else {
            _myButton.Clicked += OnMyButtonClicked;
        }
    }

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

Generally speaking, Xamarin.Forms disposes of pages when they are popped from the navigation stack. Because of this, unsubscribing from Button events is not necessary.

However, it is a best practice to use the subscribe/unsubscribe pattern outlined above. So if in doubt, do that.
