### ISSUE TITLE
In-App purchase and AdMob Sample

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [xamarin/xamarin-forms-samples#196]
Please share sample about In-App Purchase and AdMob for Xamarin.Forms include UWP project inside.
Thank you!

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

The purpose of this repository is to demonstrate how to use different Xamarin.Forms functionality, rather than third party services such as in-app purchasing and adverts. Additionally, there are so many services for providing that functionality, it would be impossible to please everyone.
