### ISSUE TITLE
MasterDetailPage in .NetStandard 

### ISSUE THREAD

**Issue by JoelP121** [xamarin/xamarin-forms-samples#259]
Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. |
I recently tried to implement the MasterDetailPage into a project. The example in XAML for ".Net Standard" does not work.  Error shown above. I even tried to directly replicate it from your example. 
The issue occurs at:
 <MasterDetailPage.Master>
        <local:MasterPage x:Name="masterPage" />
  </MasterDetailPage.Master>

The fix? I ended up using the C# version. No issues in the slightest.

Now that PCL's are replaced with .Net Standard can we possibly update all these examples to reflect the changes?

Cheers, 
J

**Comment by erotavlas** [comment]
Yeah seriously, this is really confusing now.  Microsoft should be releasing documentation and sample updates ALONG with their code updates, otherwise don't release them.  So much wasted time on our part.

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I've been able to convert the PCL project in the sample to a .NET Standard project and run the XAML code without any problems.

With regards to converting all samples to use .NET Standard libraries instead of PCLs, this is something that will happen. But there are pre-requisites necessary for this to happen (including VSMac creating .NET Standard libs instead of PCLs), and those aren't entirely met yet.
