### ISSUE TITLE
DataPagesDemo not working in iOS Release mode

### ISSUE THREAD

**Issue by KevinvdBurg** [xamarin/xamarin-forms-samples#265]
After building and deploying the iOS Release build of this demo the app instantly crashes. If I use the Debug build the app works.

I figured out that if I remove <ResourceDictionary MergedWith="mytheme:LightThemeResources" /> in the App.xml it works but then nothing shows on the screen.

This is also my guess that the themes are still at prerelease see "#254 Question: Why Themes is still in prerelease ?"

**Comment by davidbritch** [comment]
Hi @KevinvdBurg 

This is actually a problem with Themes rather than Pages. Typically the linker will optimise themes out in release mode. While this can be stopped, some themes don't work in release mode.

This is an issue for the engineering team, and I've logged an issue in their repo - https://github.com/xamarin/Xamarin.Forms/issues/3117
