### ISSUE TITLE
Duplicate Parse Code across iOS and Android Projects

### ISSUE THREAD

**Issue by fabiogomezdiaz** [xamarin/xamarin-forms-samples#324]
### Sample
https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoParse

### Description
Is there a way to use Parse within a Xamarin Forms project without re-writing the same code? For example, the following 2 links show the same `ParseStorage` Class with the same code in both iOS and Droid projects

- https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoParse/iOS/ParseStorage.cs
- https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoParse/Droid/ParseStorage.cs

### Steps to Reproduce
N/A

### Expected Behavior
Share Parse logic code across iOS and Droid projects.

### Actual Behavior
Same `ParseStorage` class is written in both iOS and Droid projects.

- https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoParse/iOS/ParseStorage.cs
- https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoParse/Droid/ParseStorage.cs

### Information
- IDE and IDE version: Visual Studio 2017 v15.6.7 / Visual Studio Mac v7.5 Preview
- Platform with the issue: All
- Device or simulator/emulator: Both

**Comment by conceptdev** [comment]
Not at the time the sample was written: see https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoParse/iOS/TodoParse.iOS.csproj#L78 – the iOS and Android projects referenced platform-specific Parse libraries, so this could not be done in the shared code. 

Parse has since been discontinued, so this sample is effectively unsupported. Please see our Azure samples, which have PCL or .NET Standard libraries where the data handling code _can_ be shared.
