### ISSUE TITLE
Additional space occurs while cutting and pasting the text in the Entry(In iOS simulator)

### ISSUE THREAD

**Issue by shivagurunathan** [xamarin/xamarin-forms-samples#361]
### Sample

Please find the attached sample to reproduce the issue.

### Description

Additional space occurs while cutting and pasting the text in the Entry.

### Steps to Reproduce

1. Run the sample
[PastingIssue.zip](https://github.com/xamarin/xamarin-forms-samples/files/2339142/PastingIssue.zip)

2. Select all in the 1st entry and cut the text.
3. Now paste it in the 2nd Entry.

4. Note that a additional space has been included at the last.

Issue occurs in Xamarin.Forms.iOS simulators. I have checked with iPhone 8 and iPhone X simulator. Version - iOS 11.0

### Expected Behavior

Space must not get appear while pasting the text in Entry.

### Actual Behavior

Issue: Space occurs while pasting the text.

**Comment by conceptdev** [comment]
@shivagurunathan if you believe there is a problem with one of the samples in this repo, could you point to the sample you are using.

If you believe there to be a bug in Xamarin.Forms, please report it directly on the open source repo
https://github.com/xamarin/xamarin.forms Please also validate on real devices, since simulators are not always an accurate representation of how the code will behave on device.
