### ISSUE TITLE
TodoAzure Sample fails to build if target framework is set to "Use latest installed platform"

### ISSUE THREAD

**Issue by OlgaBoiarshynova** [xamarin/xamarin-forms-samples#362]
### Sample

https://github.com/xamarin/xamarin-forms-samples/blob/07166139f4abc4c26f532cd6382494e621fc05fb/WebServices/TodoAzurePush/TodoAzure.sln

### Description

TodoAzure Sample fails to build if TodoAzure.Droid project target framework is set to "Use latest installed platform". This options is set by default for the sampe, so that the newly checked out sample fails to build.

### Steps to Reproduce

1. Checkout https://github.com/xamarin/xamarin-forms-samples/blob/07166139f4abc4c26f532cd6382494e621fc05fb/WebServices/TodoAzurePush/TodoAzure.sln
2. Open Solution in IDE
3. Build Solution

### Expected Behavior
Sampe is built

### Actual Behavior
Build fails with the following failure
“/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/xbuild/Microsoft/NuGet/Microsoft.NuGet.targets(5,5): : Your project is not referencing the “MonoAndroid,Version=v8.1” framework. Add a reference to “MonoAndroid,Version=v8.1" in the “frameworks” section of your project.json, and then re-run NuGet restore. (TodoAzure.Droid)”

### Information

- IDE and IDE version: Visual Studio Enterprise 2017 for Mac Version 7.6.2 (build 33)
- Platform with the issue: 
  - iOS: 11.14.0.14
  - Android: 9.0.0.19
  - UWP:  
- Device or simulator/emulator:

**Comment by conceptdev** [comment]
Since this issue was raised, we did a bulk update of all samples to remove the `AndroidUseLatestPlatformSdk`

https://github.com/xamarin/xamarin-forms-samples/pull/371

The **TodoAzure.Droid.csproj** file now correctly references 8.1

https://github.com/xamarin/xamarin-forms-samples/blob/07166139f4abc4c26f532cd6382494e621fc05fb/WebServices/TodoAzurePush/Droid/TodoAzure.Droid.csproj#L18

Thanks for reporting this issue.
