### ISSUE TITLE
[iOS] Localization sample is treating ms-MY as an invalid .NET culture

### ISSUE THREAD

**Issue by adrianknight89** [xamarin/xamarin-forms-samples#365]
iOS localization sample is incorrectly assuming that ["ms-MY"](https://github.com/xamarin/xamarin-forms-samples/blob/58c9cbbdfd4fc476a3f42f53b2208858defcf541/UsingResxLocalization/iOS/Localize.cs#L65) is an invalid culture, which is not true according to https://azuliadesigns.com/list-net-culture-country-codes/. 

Also, we should look into leveraging `CultureInfo.DefaultThreadCurrentCulture` and `CultureInfo.DefaultThreadCurrentUICulture` when setting locale. https://weblogs.asp.net/morteza/how-to-set-currentculture-for-all-threads-in-a-domain-in-net-4-5

EDIT: On Android, ms-BN and ms-MY should be excluded as well.

**Comment by conceptdev** [comment]
Which sample are you referring to? Note in the **UsingResxLocalization** sample, there is code that explicitly looks for unsupported cultures and helps with resolving them, eg

iOS
https://github.com/xamarin/xamarin-forms-samples/blob/master/UsingResxLocalization/iOS/Localize.cs#L63-L74

Android
https://github.com/xamarin/xamarin-forms-samples/blob/master/UsingResxLocalization/Android/Localize.cs#L59-L74

I would recommend following a pattern like this for your apps.

**Comment by adrianknight89** [comment]
I'm referring to the samples you provided. In those switch blocks, ms-MY and ms-BN should not be included.

**Comment by conceptdev** [comment]
At the time that sample was updated, those locales were definitely throwing an exception (and not falling back to "ms" as you'd expect), which is why the switch statement exists. I've just tested and verified that "ms-MY" seems to work now; although the "gsw-CH" example still requires the special case.

Specific locales may or may not work (or be added over time), so the best advice is to test thoroughly with the locales you wish to support, and ensure you fail gracefully for those you cannot predict. 

The sample code will be updated to reflect your comments above - thanks for taking the time to let us know.
