### ISSUE TITLE
GetInfoContents(Marker marker) is not being called with denied localization permission

### ISSUE THREAD

**Issue by eltonmrk** [xamarin/xamarin-forms-samples#402]
### Sample

```
protected override void OnElementChanged(Xamarin.Forms.Platform.Android.ElementChangedEventArgs<Map> e)
        {
            base.OnElementChanged(e);

            if (e.OldElement != null)
            {
                NativeMap.InfoWindowClick -= OnInfoWindowClick;
            }

            if (e.NewElement != null)
            {
                var formsMap = (CustomMap)e.NewElement;
                customPins = formsMap.CustomPins;
                Control.GetMapAsync(this);
            }
        }
```

### Description

`GetInfoContents` is only called when localization permission has been enabled. `Control` needs to be cast to `MapView`, e.g. `((MapView)Control).GetMapAsync(this);`.

### Steps to Reproduce

1. Implement custom renderer and add some pins.
2. Deny localization permission.
3. Open maps view. 
4. Debug into `GetInfoContents()`.

### Expected Behavior
`GetInfoContents()` should be called. 

### Actual Behavior
`GetInfoContents()` won't be called. 

### Information

- IDE and IDE version: Visual Studio Mac v7.4
- Platform with the issue: 
- Android: 8.0

**Comment by davidbritch** [comment]
Hi @eltonmrk 

Apologies for the length of time this issue has been open and unresponded too. The code has changed since you logged the issue, and the call to `GetMapAsync` is no longer necessary, as it's performed by Xamarin.Forms.Maps now.

The `GetInfoContents` method is implemented as part of the `GoogleMap.IInfoWindowAdapter` interface. So Xamarin.Forms has no control over when `GetInfoContents` is invoked or not. Xamarin.Essentials can be used to ensure that location permissions are enabled.
