### ISSUE TITLE
PhotoWrappingPage of project FlexLayoutDemos refers to unavailable stock.json file

### ISSUE THREAD

**Issue by jlt911** [xamarin/xamarin-forms-samples#465]
### Steps to Reproduce

1.
2.
3.

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 
  - UWP:  
- Device or simulator/emulator:

**Comment by jlt911** [comment]
This piece of code points to an object that is not available anymore.
// Download the list of stock photos
Uri uri = new Uri("http://docs.xamarin.com/demo/stock.json");

This is used for the PhotoWrappingPage page. Is there somewhere else I can get the file to make the sample page work ? thank you.

**Comment by davidbritch** [comment]
This sample was updated a month ago, with a correct URL (https://raw.githubusercontent.com/xamarin/docs-archive/master/Images/stock/small/stock.json). However, you'll have to clone the repo to see this. The downloadable zip files haven't been updated, due to behind the scenes work to move our samples gallery.
