### ISSUE TITLE
Update TodoAzureAuthADB2CClientFlow MSAL code to latest release of MSAL

### ISSUE THREAD

**Issue by norton287** [xamarin/xamarin-forms-samples#467]
https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoAzureAuthADB2CClientFlow

### Description

Update code to reflect latest MSAL update

### Steps to Reproduce

Code in the app shows as obsolete versus latest MSAL release

**Comment by profexorgeek** [comment]
Hi @norton287 
I fetched and built the sample to test and here's the current story. The short answer is that if you use MSAL 2.X the sample should continue to work fine. MSAL has seen to major version updates over the last month and a half that introduce breaking changes.

When I last updated the sample, MSAL 3.X was still in preview and 2.X was the stable version. MSAL 3.X primarily adds a builder-based instantiation system and support for custom domains but this is a breaking change. It hit a stable release after this sample was updated. If you want to use 3.X you will have to change the instantiation of the client to use the builder system. You can read more about the v3 changes here:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-3-released

MSAL v4 just dropped yesterday. It introduces breaking changes due to asynchronous token cache serialization. You can read more about these changes here:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/msal-net-4

The roadmap for MSAL, and general documentation are available here and are frequently updated:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki
