### ISSUE TITLE
Forms Gallery: Lack of Xaml / Out of Date

### ISSUE THREAD

**Issue by Mike-EEE** [xamarin/xamarin-forms-samples#51]
I have been looking through the Forms Gallery code.  It does seem a little out-dated, and it also appears to not use Xaml, and favors C# code instead.  This can be seen as providing poor (and at the very least, inconsistent) guidance, as Xaml (as you well know :)) is quite excellent at defining controls and UI (and really, _anything_! ... which is why it's so awesome).

I have a Xamarin.Forms project I am working on, and the FormsGallery is a perfect solution for what I am looking to do for test purposes.  I took the day to update the code in the FormsGallery project to Xaml, and to introduce some improvements with the use of bindings over event handlers (and Behaviors in some cases).  In addition to upgrading the project to 1.3.5, I have also updated the Fonts to use the recommended attributes.  I've also found some questions/issues I would like to start some discussion around, if possible:

1) I have found that there is inconsistent use of navigation throughout the FormsGallery.  For instance, HomePage uses ICommand while NavigationPageDemoPage uses Click handlers.  In my efforts, I have updated all navigation to use ICommand implementations.
2) I have found that the font size of the header label is inconsistent throughout the library.  It ranges from 30, 40 and 50, and I am curious if this is by design or if there is a desire to get these consistent?
3) I did find the SearchBar sort of confusing while using it for the first time a few weeks ago.  It requires that you know of the exact property to search for... and for someone who is just starting out, they might not have any idea of what this is and as a result the control feels broken.  In my implementation, I changed it from a "Equals" search to a "StartsWith" search.

You can see my current efforts here:
https://github.com/Michael-DST/xamarin-forms-samples/tree/master/FormsGallery/FormsGallery/FormsGallery

I have everything converted to Xaml with the exception of RelativeLayoutDemoPage.  I should have this done tomorrow (along with actually testing this all out _smile_).  Please note that I have currently kept the original .cs files in the repository, but they are no longer referenced in the .csproj file.

I would be interested to know if the team themselves would be interested in a PR to see the changes once I am done.  I would love to assist here in any way possible.  Xamarin.Forms is really awesome and this has been an even awesomer way of getting familiar to the code and all its glorious constructs. :)

And also, again, no worries if this is not wanted.  I had to do this for my current project, so I figure I would check in here to see if this project might benefit from my efforts as well.  I am a big believer in Xaml and would Xamlify the entire world if I could, haha.  

Finally, I do realize you have a XamlSamples section in this project.  I would argue that everything as much as possible should be Xaml, from a guidance (and consistency) perspective.  The last thing we need is to get some junior developers seeing code that should be written in Xaml and copy/paste into their own projects.  Let's also remember that Xaml was/is meant to be language-agnostic (in addition to being designer-friendly, as your samples section rightly mentions).  And while Xamarin.Forms might only work with C# at the moment, I would like to think that it will eventually grow big enough to support other languages in the future.  Xaml enables this natural progression rather than hinder it.

Thank you for any consideration!

**Comment by conceptdev** [comment]
Wow @Michael-DST that's a lot of work. Thanks for sharing it.

You'll notice that in many samples (especially the "Working with..." series) we do our best to build everything in *both* C# and XAML. Rather than 'convert' this sample to XAML instead of C#, it would be more fitting with our strategy to offer both, and let our customers compare and contrast them. This of course creates a sample-maintenance-overhead, but sometimes that's worth it.

I can't speak directly to some of the other differences you pointed out. Click handlers versus ICommand for example could have been a conscious choice by the authors to demonstrate that different methods are possible and can be combined; or it could be an oversight. In this specific example, the navigation (ie. the HomePage) isn't intended to be on show, rather the individual pages are the important part; and we've probably kept the NavigationPageDemo "simple" and approachable for beginners.

We'll have a look at the code you've submitted. While we can't accept this PR (we don't want to lose the C# version) there may be other ways we can surface your work in the future.

**Comment by davidbritch** [comment]
Apologies for the delayed response, but I'm pleased to let you know that the FormsGallery sample has now been updated and also includes XAML pages.
