### ISSUE TITLE
CollectionViewDemos on Android arent displaying any images & group examples only display header names

### ISSUE THREAD

**Issue by davefxy** [xamarin/xamarin-forms-samples#535]
### Sample

 https://github.com/xamarin/xamarin-forms-samples/UserInterface/CollectionViewDemos
### Description
CollectionViewDemos  arent displaying any images & group examples only display header names.
Xaminals sample works fine which uses same images.

### Steps to Reproduce

1.
2.
3.

### Actual Behavior
Group samples gets folllowing error for each group member:
[0:] Binding: 'ImageUrl' property not found on 'Bears', target property: 'Xamarin.Forms.Image.Source'
[0:] Binding: 'Location' property not found on 'Bears', target property: 'Xamarin.Forms.Label.Text'

Vertical list (DataTemplate) sample gets following error for each image:
[0:] ImageLoaderSourceHandler: Could not retrieve image or image data was invalid: Uri: http://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Papio_anubis_(Serengeti%2C_2009).jpg/200px-Papio_anubis_(Serengeti%2C_2009).jpg
10-11 10:57:45.221 D/skia    ( 9767): --- SkAndroidCodec::NewFromStream returned null

### Information

- IDE and IDE version: 
Visual Studio 2019 v16.3.4
- Platform with the issue: 
Android SDK 9.0
- Device or simulator/emulator: 
Samsung SM-T810 (Android 7.0 - API 24)

**Comment by davidbritch** [comment]
Hi @davefxy 

So there's two issues here: grouping, and lack of images.

In Xamarin.Forms 4.2 (which the sample uses), CollectionView grouping is only implemented for iOS. Grouping support for Android has been added in Xamarin.Forms 4.3 (currently a pre-release, but due to move to a stable release any day now).

The image issue is a problem with image caching in Xamarin.Forms 4.2. For more info, see https://github.com/xamarin/Xamarin.Forms/issues/7751#issuecomment-536694500

As these are issues with Xamarin.Forms, rather than the sample, I'm going to close this issue.
