### ISSUE TITLE
VideoPlayer with controls enabled not working properly inside a ListView control

### ISSUE THREAD

**Issue by Tmaturano** [xamarin/xamarin-forms-samples#549]
### Description
![videoPlayer](https://user-images.githubusercontent.com/13560048/68328542-44fd9380-00ae-11ea-81f1-2175657eb07b.gif)

I have a simple videoPlayer with` AreTransportControlsEnabled="True"` using the FormsVideoLibrary, that is inside of each ViewCell of a ListView. 
When I scroll down or up the videos in the ListView, the TransportControls are moving together with the scroll.
It only happens on Android. 

### Steps to Reproduce

1. Add a VideoPlayer in a ListView ViewCell and let the AreTransportControlsEnabled **True**
2. Play the Video with the controls displayed and start to scroll up or down

### Expected Behavior
The controls should be inside the Video Component

### Actual Behavior
The controls are moving away from the component.

### Information

- IDE and IDE version:  Visual Studio 2019 v16.3.7  
- Platform with the issue: Windows / Mac 
  - Android: Android 9.0 + I didn't test in previous Android versions
- Device or simulator/emulator:  Device and android emulator

**Comment by davidbritch** [comment]
Hi @Tmaturano 

This sample was only ever intended to be just that: a sample that shows how to play videos, rather than a fully fledged video control that works in all situations.

For a fully fledged video control, I recommend you check out the `MediaElement` control that should drop in a Xamarin.Forms pre-release next week.
