### ISSUE TITLE
Web video and Resource Video doesnot load in Android 8.1 API 27 and 28

### ISSUE THREAD

**Issue by cris-m** [xamarin/xamarin-forms-samples#586]
unable to load web video in android 8.1 API 28 Emulator, i tested in android 8.1 API 27 and it work perfectly . Resource video does not load either in API 28 or API 27. ms-appx:/// url doesnot work to load embedded resource from android raw folder

**Comment by davidbritch** [comment]
Hi @cris-m 

I wrote [the sample](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/MediaElementDemos) and tested it in API 28. I've just ran it again in API28 and for me it plays web videos, and app package videos (using ms-appx:///).

With that said, there are a lot of bugs in `MediaElement`, which is why it's behind the experimental flag.

**Comment by cris-m** [comment]
experimental
