### ISSUE TITLE
ItemAppearing Event not triggered on iOS Custom Cell Renderer ("C" Folder")

### ISSUE THREAD

**Issue by BitterSymphony** [xamarin/xamarin-forms-samples#65]
Thanks for your great sample for demonstrating listview native cell renderer.
But I found that the listview's ItemAppearing event is not being triggered on iOS Custom Cell Renderer, Could you please take a look into it :)?

**Comment by Arpit360** [comment]
I have checked this issue with sample https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithListviewNative  and observed that event is  being triggered on iOS Custom Cell Renderer.

Screencast : http://www.screencast.com/t/XQWq5is7gtP

Please review my screencast and let me know if you are facing this issue again.

Also provide me the environment Info and xamarin.Forms version on which you are facing this issue.

Thanks

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue.

I can confirm that in the latest stable release of Xamarin.Forms, the `ListVIew.ItemAppearing` event isn't firing on the code in the C folder. However, this is by design. The mechanism that causes the `ItemAppearing` event to bubble up on iOS must be implementation in the Xamarin.Forms native cell implementation. For how to do this, see https://bugzilla.xamarin.com/show_bug.cgi?id=34014#c1.
