### ISSUE TITLE
ShapesDemos broken

### ISSUE THREAD

**Issue by sjorsmiltenburg** [xamarin/xamarin-forms-samples#681]
Today I ran the xamarin-forms-samples/UserInterface/ShapesDemos/

On Android also not all samples work
- only a quarter of the analog clock demo is rendered.
- the flower demo seems broken with only a part rendered

On UWP a lot of the samples don't show up or render completely
- flower demo -> does not show anything
- baby elephant demo -> does not show anything

also, on uwp it renders for me on a black background, (because of black windows theme?) making the cat sample and the analog clock sample invisible.

**Comment by Siphonophora** [comment]
I ran into the same issues testing the shapes on the android emulator noted by @sjorsmiltenburg . 

I'm particularly interested in why the clock hands don't rotate in the example. I tried following the pattern shown in my own app and updating the Angle bound to `RotateTransform` didn't result the path being rotated over time. I tried both the bindable property on the view and a full property with INotifyPropertyChanged on the view model. Neither of these worked. I suspect some sort of issue with the binding itself, because initializing the backing field in the view model to 50, didn't result in the initial render of the path being rotated. That only seemed to happen if I put 50 in the `RotateTransform` without binding.

![image](https://user-images.githubusercontent.com/32316111/111074153-1076c480-84b8-11eb-9319-d9ee028d888a.png)

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms. Its documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0) and its samples can be found [here](https://github.com/dotnet/maui-samples).
